# Generated by Django 5.0.7 on 2024-08-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
